export const INDUSTRY_TYPES = [
  "Agriculture",
  "Automobile Transport",
  "Ecommerce",
  "Education",
  "Financial Institution",
  "Gym",
  "Hospitality",
  "IT Company",
  "Lifestyle Clubs",
  "Logistics",
  "Marriage Bureau",
  "Media & Advertisement",
  "Personal Use",
  "Political",
  "Real estate",
  "Retail & FMCG",
  "Stock & Commodity",
  "Telecom",
  "Tips & Alert",
  "Travel",
  "Wholesalers Distributors or Manufacturers",
];
 