import { motion, AnimatePresence, useScroll, anticipate, useInView } from "framer-motion";
import { useEffect, useState } from "react";
import { useRef } from "react";
import { Menu } from "lucide-react";
import { RxCaretUp } from "react-icons/rx";
import { FaLink, FaWhatsapp } from "react-icons/fa";
import { BsInstagram, BsRobot } from "react-icons/bs";
import { SiCivicrm } from "react-icons/si";
import { IoIosLink } from "react-icons/io";
import { FaRobot, FaArrowRight } from "react-icons/fa";
import { GiArtificialIntelligence } from "react-icons/gi";
import { GiBlast } from "react-icons/gi";
import { CgMenuLeft } from "react-icons/cg";
import { FaSortAmountUp } from "react-icons/fa";
import { TbAutomation } from "react-icons/tb";
import { LiaLinkedin, LiaToolsSolid } from "react-icons/lia";
import { SiCustomink } from "react-icons/si";
import { TbTargetArrow } from "react-icons/tb";
import { FaStore } from "react-icons/fa";
import { TbReportSearch } from "react-icons/tb";
// import ToggleButton from "../../src/components/subscription/ToggleButton";
// import ToggleSwitch from "../components/ToggleSwitch";
import { MdRocketLaunch } from "react-icons/md";
import { useGSAP } from "@gsap/react";
import { IoStarOutline } from "react-icons/io5";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { CiFacebook } from "react-icons/ci";
import { FaInstagram } from "react-icons/fa";
// import { Link } from "lucide-react";
import { CiLinkedin } from "react-icons/ci";
import { RxCross2 } from "react-icons/rx";
import { TiTick } from "react-icons/ti";
import { GiDiamondTrophy } from "react-icons/gi";
import { Link } from "react-router-dom";
import { useTenant } from "../context/TenantContext";


gsap.registerPlugin(ScrollTrigger);




function AnimatedCounter({ target, currency, duration, trigger }) {
    const [count, setCount] = useState(0);


    useEffect(() => {
        if (!trigger) return;

        let start = 0;
        const increment = target / (duration / 16);
        const step = () => {
            start += increment;
            if (start < target) {
                setCount(Math.floor(start));
                requestAnimationFrame(step);
            } else {
                setCount(target);
            }
        };
        step();
    }, [trigger, target, duration]);

    return (
        <div className="text-primary-700 text-center text-5xl font-extrabold tracking-tight">
            {currency || ""}{count.toLocaleString()}+
        </div>
    );
}
const stats = [
    {
        value: 50000,
        label: "Businesses Have boosted their sales in up to 70% using our tools to automate their social media.",
    },
    {
        value: 2000,
        label: "Agencies have automated their operations and increased their performance with Sabnode.",
    },
    {
        value: 800000,
        label: "Revenue generated by our users using our marketing automation platform.",
        currency: "Rs ",
    },
];

const tabs = [
    {
        id: "wachat",
        label: "Wachat",
        title: "Whatsapp Marketing and Automation",
        icon: <FaWhatsapp />,
        description:
            "Boost your engagement and conversions with automated WhatsApp marketing. Schedule messages, respond instantly, and stay connected effortlessly.",
        color: "green",

    },
    {
        id: "botpain",
        label: "Botpain",
        title: "All in One Social Media Automation",
        icon: <BsRobot />,
        description:
            "Automate posts, messages, and audience interactions across social platforms with ease. Your AI social media manager is here.",
        color: "green",
    },
    {
        id: "crm",
        label: "CRM",
        title: "Customer Relationship Management",
        icon: <SiCivicrm />,
        description:
            "Manage leads, track interactions, and build long-term customer relationships. Everything you need in one CRM dashboard.",
        color: "green",
    },
    {
        id: "biolink",
        label: "Bio Link",
        title: "Drag-and-drop BioLinks page builder",
        icon: <IoIosLink />,
        description:
            "Create stunning bio pages with drag-and-drop ease. Perfect for Instagram, TikTok, and other platforms.",
        color: "green",
    },
];

export default function LandingPage() {
    const [isScrolled, setIsScrolled] = useState(false);
    const [sidebarOpen, setSidebarOpen] = useState(false);
    const [showDropdown, setShowDropdown] = useState(false);
    const [activeTab, setActiveTab] = useState("wachat");
    const activeContent = tabs.find((tab) => tab.id === activeTab);
    const [subscription, setsubscription] = useState(false);
    const scrolly = useScroll().scrollYProgress;
    const sectionRef = useRef(null);
    const isInView = useInView(sectionRef, { once: true });

    const { siteConfig } = useTenant(); // Access siteConfig

    const sectionsRef = useRef([]);



    const handleIconClick = (url) => {
        if (url) window.open(url, '_blank');
    };

    const openInNewTab = (url) => {
        if (url && typeof url === 'string') {
            window.open(url, '_blank', 'noopener,noreferrer');
        }
    };


    console.log("tenants. =>>>>>>>>", siteConfig)
    const { heroSection, logoUrl, name, domain,testimonials, privacyPolicyUrl, termsOfServiceUrl, socialMediaLinks } = siteConfig;

    useEffect(() => {
        sectionsRef.current.forEach((section, index) => {
            gsap.set(section, {
                zIndex: sectionsRef.current.length - index,
                y: 100 * index, // slight offset
            });

            ScrollTrigger.create({
                trigger: section,
                start: "top center",
                end: "+=100%",
                pin: true,
                pinSpacing: false,
                scrub: true,
            });
        });
    }, []);


    const helloRef = useRef();

    const boxRef = useRef();
    const divRef = useRef();

    // useGSAP(() => {
    //   // Pin the first box when it scrolls into view
    //   gsap.to(helloRef.current, {
    //     scrollTrigger: {
    //       trigger: helloRef.current,
    //       start: "top top",
    //       end: "+=300",       // how long it's pinned
    //       pin: true,
    //       scrub: true,
    //       // markers: true,
    //     },
    //   });
    // }, []);

    // useGSAP(() => {
    //   // Animate second box to scroll up and partially cover the pinned one
    //   gsap.fromTo(
    //     boxRef.current,
    //     { y: 200 },
    //     {
    //       y: 30, // 30px below the first box
    //       scrollTrigger: {
    //         trigger: boxRef.current,
    //         start: "top center",
    //         scrub: true,
    //         pin: true,
    //         // markers: true,
    //       },
    //     }
    //   );
    // }, []);
    useEffect(() => {
        gsap.fromTo(
            divRef.current,
            { opacity: 0, y: 50 },
            {
                opacity: 1,
                y: 0,
                duration: 1,
                ease: "power2.out",
                scrollTrigger: {
                    trigger: divRef.current,
                    start: "top 80%", // when top of div hits 80% of viewport
                    toggleActions: "play none none none",
                },
            }
        );
    }, []);
    useEffect(() => {
        document.title = "Generative AI Platform";

        const handleScroll = () => {
            setIsScrolled(window.scrollY > 20);
        };

        window.addEventListener("scroll", handleScroll);
        return () => window.removeEventListener("scroll", handleScroll);
    }, []);

    const sidebarVariants = {
        hidden: { x: "100%" },
        visible: { x: 0 },
        exit: { x: "100%" },
    };

    const navItemVariants = {
        hidden: { opacity: 0, y: -10 },
        visible: (i) => ({ opacity: 1, y: 0, transition: { delay: i * 0.1 } }),
    };

    const dropdownVariants = {
        hidden: { opacity: 0, y: -10 },
        visible: { opacity: 1, y: 0, transition: { duration: 0.3 } },
    };

    return (



        <div className="bg-gradient-to-b from-violet-50 to-violet-100 min-h-screen text-black">
            <header
                className={`sticky top-0 z-50 py-4 transition duration-500 ease-in-out ${isScrolled
                    ? " backdrop-blur-2xl"
                    : "bg-primary-500"
                    }`}
            >
                <div className={`max-w-7xl  mx-auto px-6 flex justify-between items-center ${isScrolled ? " bg-white text-black rounded-full " : ""} `}>
                    <motion.div
                        initial={{ opacity: 0, x: -50 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.6 }}
                        className="text-2xl font-bold text-black "
                    >
                        <span className={`text-primary-300  ${isScrolled ? " text-primary-500" : ""} `}>{name}</span><span className={`${isScrolled ? "text-black" : "text-white"}`}></span>
                    </motion.div>

                    {(
                        <motion.button
                            initial={{ opacity: 0, scale: 0.8 }}
                            animate={{ opacity: 1, scale: 1 }}
                            whileHover={{ scale: 1.1 }}
                            onClick={() => setSidebarOpen(true)}
                            className="md:hidden p-2 md:p-0 text-black"
                        >
                            <Menu className={` ${isScrolled ? 'text-black' : "text-white"}`} size={28} />
                        </motion.button>
                    )}

                    <nav className="hidden md:flex space-x-6 text-lg">

                        {[
                            { label: "Products", dropdown: true },
                            { label: "Pricing", link: "#pricing" },
                            { label: "Resources", link: "#resources" },
                            { label: "Log in", link: "/login" },
                        ].map((item, i) => (
                            <motion.div
                                key={i}
                                custom={i}
                                initial="hidden"
                                animate="visible"
                                variants={navItemVariants}
                                className={` hover:text-primary-700 hover:underline  py-3 transition  cursor-pointer ${isScrolled ? "hover:text-primary-700 text-black " : "text-white"}`}
                                onMouseEnter={() => item.dropdown && setShowDropdown(true)}
                                onMouseLeave={() => item.dropdown && setShowDropdown(false)}
                            >
                                <Link to={item.link} className="flex items-center gap-2">
                                    {item.label}
                                    {item.dropdown && (
                                        <motion.span
                                            animate={{ rotate: showDropdown ? 180 : 0 }}
                                            transition={{ duration: 0.1, ease: "easeInOut" }}
                                        >
                                            <RxCaretUp />
                                        </motion.span>
                                    )}
                                </Link>


                                {item.dropdown && showDropdown && (
                                    <motion.div
                                        initial="hidden"
                                        animate="visible"
                                        exit="hidden"
                                        variants={dropdownVariants}
                                        className="absolute top-full left-0  mt-2 w-[100vw]  bg-white text-black  shadow-xl p-4 z-50"
                                    >
                                        <ul className="grid grid-cols-3 gap-4 w-full">
                                            {["Wachat", "Sabnode AI", "Socialproof", "Botpion", "Pingblast", "SitesPY"].map((subItem, idx) => (
                                                <li
                                                    key={idx}
                                                    className="hover:text-purple-600 transition font-medium"
                                                >
                                                    {subItem}
                                                </li>
                                            ))}
                                        </ul>
                                    </motion.div>
                                )}
                            </motion.div>
                        ))}
                    </nav>

                    <motion.button
                        whileHover={{ scale: 1.05 }}
                        className={`bg-primary-400 md:block hidden  ${isScrolled ? "text-black" : "text-white"} px-5 py-2 rounded-lg  font-semibold shadow`}
                    >
                        Get Started
                    </motion.button>
                </div>
            </header>

            <AnimatePresence>
                {sidebarOpen && (
                    <motion.aside
                        initial="hidden"
                        animate="visible"
                        exit="exit"
                        variants={sidebarVariants}
                        transition={{ duration: 0.4 }}
                        className="fixed top-0 right-0 w-72 h-full bg-primary-500 text-black p-6 shadow-2xl z-50"
                    >
                        <button
                            onClick={() => setSidebarOpen(false)}
                            className="text-right w-full text-purple-200 hover:text-black"
                        >
                            Close ✕
                        </button>
                        <ul className="mt-8 space-y-4">
                            {["Home", "Features", "About", "Contact", "login"].map((item, i) => (
                                <Link to={item}>
                                    <motion.li
                                        key={i}
                                        whileHover={{ scale: 1.05 }}
                                        className="cursor-pointer text-white hover:text-primary-300"
                                    >
                                        {item}
                                    </motion.li>

                                </Link>
                            ))}
                        </ul>
                    </motion.aside>
                )}
            </AnimatePresence>

            <div className="text-center px-6 py-16 md:py-15">
                <motion.div
                    initial={{ opacity: 0, y: 40 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8 }}
                    className="text-sm bg-primary-600 px-3 py-1 inline-block rounded-full mb-4 text-white"
                >
                    NEW YEAR SALE — Get 50% off now
                </motion.div>

                <motion.h1
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2, duration: 0.6 }}
                    className="text-4xl md:text-6xl font-bold leading-tight text-black"
                >
                    {heroSection?.title} <br />
                    <span className="text-primary-300">{heroSection?.subtitle}</span>
                </motion.h1>

                <motion.p
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.4, duration: 0.6 }}
                    className="mt-6 max-w-2xl mx-auto text-lg text-primary-500"
                >
                    Our all-in-one platform unlocks the full potential of your business and drives growth effortlessly. Empower your BI, boost conversions.
                </motion.p>

                <div className="mt-8 flex justify-center space-x-4">
                    <motion.button
                        whileHover={{ scale: 1.05 }}
                        className="bg-primary-600 hover:bg-primary-700 text-white px-6 py-3 rounded-lg font-semibold shadow"
                    >
                        {heroSection.buttonText}
                    </motion.button>

                    <motion.button
                        whileHover={{ scale: 1.05 }}
                        className="bg-white text-primary-700 px-6 py-3 rounded-lg font-semibold shadow  border-primary-500"
                    >
                        Contact Sales
                    </motion.button>
                </div>
            </div>

            <motion.div
                initial={{ opacity: 0, y: 50 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.6, duration: 0.8 }}
                className="max-w-5xl mx-auto px-6 "
            >
                <img
                    src="../images/wp.png"
                    alt="Dashboard preview"
                    className='mx-auto'
                />
            </motion.div>
            <div>
                <h2 className="text-center mt-12 mb-3 text-5xl font-extrabold">Ultimate Solution for <span className="text-green-500">Success</span></h2>
                <div className="text-sm text-center">At sabnode, we provide everything you need to attract more customer, improve retention, and scale your business-all from a single, intutive platform</div>

                <div className="w-full my-7 max-w-7xl mx-auto  px-4">


                    <div className="grid md:grid-cols-4 gap-7 py-10">

                        <div className="flex md:flex-col md:gap-9 gap-2 ">
                            {tabs.map((tab) => (
                                <button
                                    key={tab.id}
                                    onClick={() => setActiveTab(tab.id)}
                                    className={`md:px-5 px-2 py-1 rounded-md font-semibold border transition-all duration-300 shadow-sm ${activeTab === tab.id
                                        ? `bg-${tab.color}-500 text-black`
                                        : `bg-gray-100 text-gray-700 hover:bg-primary-500 hover:text-white`
                                        }`}
                                >
                                    <div className="flex flex-row  justify-center items-center md:gap-3">
                                        <div className="text-[22px]">
                                            {tab.icon}
                                        </div>
                                        <div>
                                            {tab.label}

                                        </div>

                                    </div>
                                </button>
                            ))}
                        </div>
                        <div className="md:col-span-3">
                            <AnimatePresence mode="wait">
                                <motion.div
                                    key={activeContent.id}
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    exit={{ opacity: 0, y: -20 }}
                                    transition={{ duration: 0.4 }}
                                    className=" shadow-xl md:h-[245px] rounded-2xl p-8 text-center border"
                                >
                                    <div className="grid grid-cols-[70px_1fr] gap-2 items-center justify-center mb-2">
                                        <div className={`text-[50px] text-${activeContent.color}-500 bg-white shadow-${activeContent.color}-500/50  flex justify-center items-center shadow-lg  rounded-full p-2`}>
                                            {activeContent.icon}
                                        </div>
                                        <div >
                                            <h3 className={`text-2xl  mb-4 text-${activeContent.color}-500 font-extrabold`}>
                                                {activeContent.title}
                                            </h3>
                                        </div>
                                    </div>

                                    <p className="text-black">{activeContent.description}</p>
                                    <button
                                        className={`mt-6 px-6 py-2 rounded-lg text-black bg-${activeContent.color}-500 hover:bg-${activeContent.color}-600 transition`}
                                    >
                                        Explore now →
                                    </button>
                                </motion.div>
                            </AnimatePresence>
                        </div>

                    </div>
                </div>
                <div>


                </div>
                <div>


                </div>

                <div className="w-full my-15 max-w-7xl mx-auto  px-4">

                    <div className="grid md:grid-cols-3 gap-5 justify-center items-center">

                        <div className="md:col-span-2 space-y-7 ">
                            <div className="text-3xl font-extrabold ">Automate Support With <span className="text-primary-800">AI Chatbots</span></div>
                            <div>
                                Equip an AI chatbot to deliver personalized experiences to your leads or clients’ leads. Offer seamless, round-the-clock support and foster interactive conversations that boost conversions.
                            </div>
                            <button className="inline-flex items-center gap-3 px-6 py-3 bg-primary-600 text-white rounded-full shadow-lg hover:bg-primary-500 transition">
                                <FaRobot className="text-xl" />
                                Explore Now
                                <FaArrowRight />
                            </button>
                        </div>
                        <div>
                            <img src={heroSection.image} alt="sabnode demo" />
                        </div>
                    </div>
                </div>
            </div>
            <div className="w-full my-15 max-w-7xl mx-auto  px-4">
                <div className="text-red-500 mt-5 text-xl text-center">Apps</div>

                <div className="relative hidden md:flex  w-full relative h-[500px] relative border border-primary-500 rounded-lg overflow-hidden flex justify-center items-center">
                    <div className="absolute top-0 left-0 flex items-center justify-center absolute ">
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: 0,
                                top: 0,
                                right: 1000,
                                bottom: 400
                            }}
                            animate={{
                                y: 66,
                                x: 107
                            }} transition={{
                                duration: 2,
                                delay: 1,
                                ease: anticipate
                            }} className="w-[120px] flex gap-2 text-green-500 flex-col justify-center items-center h-[120px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-green-400">
                            {/* Optional inner shine */}
                            <div className="text-[22px]">
                                <FaWhatsapp />
                            </div>
                            <div className="text-green-500 font-bold text-xl">Wachat</div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: 0,
                                top: 0,
                                right: 800,
                                bottom: 400
                            }}
                            animate={{
                                x: 720,
                                y: 177
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[120px] flex gap-2 text-purple-500 flex-col justify-center items-center h-[120px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow-[0_0_20px_rgba(168,85,247,0.6)]">
                            {/* Optional inner shine */}
                            <div className="text-[22px]">
                                <FaRobot />
                            </div>
                            <div className="text-purple-500 font-bold text-xl">Botpion</div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: 0,
                                top: 0,
                                right: 800,
                                bottom: 400
                            }}
                            animate={{
                                x: 24,
                                y: 138
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[120px] flex gap-2 text-yellow-500 flex-col justify-center items-center h-[120px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-yellow-500">
                            {/* Optional inner shine */}
                            <div className="text-[22px]">
                                <SiCivicrm />
                            </div>
                            <div className="text-yellow-500 font-bold text-xl">Crm</div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: 0,
                                top: 0,
                                right: 800,
                                bottom: 400
                            }}
                            animate={{
                                y: 8
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[120px] flex gap-2 text-green-500 flex-col justify-center items-center h-[120px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-blue-500">
                            {/* Optional inner shine */}
                            <div className="text-[22px] text-blue-500">
                                <FaLink />
                            </div>
                            <div className="text-blue-500 font-bold text-xl">BioLink</div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -500,
                                top: 0,
                                right: 400,
                                bottom: 400
                            }}
                            animate={{
                                x: 311,
                                y: 14
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[120px] flex gap-2 text-green-500 flex-col justify-center items-center h-[120px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-pink-500">
                            {/* Optional inner shine */}
                            <div className="text-[22px] text-blue-500">
                                <GiArtificialIntelligence className="text-pink-500" />

                            </div>
                            <div className="text-pink-500 font-bold text-xl">SabnodeAI</div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -600,
                                top: 0,
                                right: 400,
                                bottom: 400
                            }}
                            animate={{
                                x: 207,
                                y: 348
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[120px] flex gap-2 text-green-500 flex-col justify-center items-center h-[120px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-black">
                            {/* Optional inner shine */}
                            <div className="text-[22px] text-blue-500">
                                <GiBlast className="text-black" />

                            </div>
                            <div className="text-black font-bold text-xl">PingBlast</div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -700,
                                top: 0,
                                right: 400,
                                bottom: 400
                            }}
                            animate={{
                                x: -357,
                                y: 364
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[120px] flex gap-2 text-green-500 flex-col justify-center items-center h-[120px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-orange-500">
                            {/* Optional inner shine */}
                            <div className="text-[22px] text-blue-500">
                                <CgMenuLeft className="text-orange-500" />

                            </div>
                            <div className="text-orange-500 font-bold text-xl">Solvdesk
                            </div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -800,
                                top: 0,
                                right: 300,
                                bottom: 400
                            }}
                            animate={{
                                x: -587,
                                y: 282
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[120px] flex gap-2 text-pink-500 flex-col justify-center items-center h-[120px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-pink-500">
                            {/* Optional inner shine */}
                            <div className="text-[22px] text-blue-500">
                                <FaSortAmountUp className="text-pink-500" />

                            </div>
                            <div className="text-pink-500 font-bold text-xl">uptime
                            </div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -800,
                                top: 0,
                                right: 200,
                                bottom: 400
                            }}
                            animate={{
                                x: 101,
                                y: 44
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[120px] flex gap-2 text-pink-500 flex-col justify-center items-center h-[120px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-green-500">
                            {/* Optional inner shine */}
                            <div className="text-[22px] text-blue-500">
                                <FaWhatsapp className="text-green-500" />

                            </div>
                            <div className="text-green-500 font-bold text-xl">BulkReply
                            </div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute  top-1 left-1 blur-sm" />
                        </motion.div>
                    </div>
                    <div className="w-[400px] h-[400px]  rounded-full bg-white flex  justify-center  items-center">
                        <div className="text-lg font-extrabold text-center text-black  ">
                            <div className="space-y-4 flex flex-col">
                                <div>
                                    Our <span className="text-primary-500">Apps</span> that made for <span className="text-primary-500">US</span>
                                </div>
                                <button className="inline-flex text-sm items-center gap-3 px-6 py-2 bg-primary-600 text-white rounded-full shadow-lg hover:bg-primary-700 transition">
                                    <FaRobot className="text-md" />
                                    View All Apps
                                    <FaArrowRight className="text-md" />
                                </button>
                            </div>
                        </div>

                    </div>
                </div>
                {/* for mobile */}

                <div className="relative  block md:hidden w-full relative h-[500px] relative border border-purple-800 rounded-lg overflow-hidden flex justify-center items-center">
                    <div className="absolute top-0 left-0 flex items-center justify-center absolute ">
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: 0,
                                top: 0,
                                right: 1000,
                                bottom: 400
                            }}


                            animate={{
                                y: 48,
                                x: 42
                            }}
                            transition={{
                                duration: 2,
                                delay: 1,
                                ease: anticipate
                            }} className="w-[100px] flex gap-2 text-green-500 flex-col justify-center items-center h-[100px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-green-400">
                            {/* Optional inner shine */}
                            <div className="text-[22px]">
                                <FaWhatsapp />
                            </div>
                            <div className="text-green-500 font-bold text-xl">Wachat</div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -200,
                                top: 0,
                                right: 800,
                                bottom: 400
                            }}
                            animate={{
                                x: -89,
                                y: 286
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[100px] flex gap-2 text-purple-500 flex-col justify-center items-center h-[100px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow-[0_0_20px_rgba(168,85,247,0.6)]">
                            {/* Optional inner shine */}
                            <div className="text-[22px]">
                                <FaRobot />
                            </div>
                            <div className="text-purple-500 font-bold text-xl">Botpion</div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -200,
                                top: 0,
                                right: 400,
                                bottom: 400
                            }}
                            animate={{
                                x: 90,
                                y: 175
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[100px] flex gap-2 text-yellow-500 flex-col justify-center items-center h-[100px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-yellow-500">
                            {/* Optional inner shine */}
                            <div className="text-[22px]">
                                <SiCivicrm />
                            </div>
                            <div className="text-yellow-500 font-bold text-xl">Crm</div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -300,
                                top: 0,
                                right: 800,
                                bottom: 400
                            }}
                            animate={{
                                x: -150,
                                y: 8
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[100px] flex gap-2 text-green-500 flex-col justify-center items-center h-[100px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-blue-500">
                            {/* Optional inner shine */}
                            <div className="text-[22px] text-blue-500">
                                <FaLink />
                            </div>
                            <div className="text-blue-500 font-bold text-xl">BioLink</div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -500,
                                top: 0,
                                right: 200,
                                bottom: 400
                            }}
                            animate={{
                                x: -408,
                                y: 163
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[100px] flex gap-2 text-green-500 flex-col justify-center items-center h-[100px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-pink-500">
                            {/* Optional inner shine */}
                            <div className="text-[22px] text-blue-500">
                                <GiArtificialIntelligence className="text-pink-500" />

                            </div>
                            <div className="text-pink-500 font-bold text-lg">SabnodeAI</div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -500,
                                top: 0,
                                right: 200,
                                bottom: 400
                            }}
                            animate={{
                                x: -246,
                                y: 53
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[100px] flex gap-2 text-green-500 flex-col justify-center items-center h-[100px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-black">
                            {/* Optional inner shine */}
                            <div className="text-[22px] text-blue-500">
                                <GiBlast className="text-black" />

                            </div>
                            <div className="text-black font-bold text-xl">PingBlast</div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -700,
                                top: 0,
                                right: 400,
                                bottom: 400
                            }}
                            animate={{
                                x: -347,
                                y: 279
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[100px] flex gap-2 text-green-500 flex-col justify-center items-center h-[100px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-orange-500">
                            {/* Optional inner shine */}
                            <div className="text-[22px] text-blue-500">
                                <CgMenuLeft className="text-orange-500" />

                            </div>
                            <div className="text-orange-500 font-bold text-xl">Solvdesk
                            </div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -800,
                                top: 0,
                                right: 300,
                                bottom: 400
                            }}
                            animate={{
                                x: -581,
                                y: 335
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[120px] flex gap-2 text-pink-500 flex-col justify-center items-center h-[120px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-pink-500">
                            {/* Optional inner shine */}
                            <div className="text-[22px] text-blue-500">
                                <FaSortAmountUp className="text-pink-500" />

                            </div>
                            <div className="text-pink-500 font-bold text-xl">uptime
                            </div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                        <motion.div
                            initial={{
                                y: [-300],
                            }}
                            drag
                            dragConstraints={{
                                left: -800,
                                top: 0,
                                right: 200,
                                bottom: 400
                            }}
                            animate={{
                                x: 101,
                                y: 44
                            }} transition={{
                                duration: 3,
                                delay: 2,
                                ease: anticipate
                            }} className="w-[120px] flex gap-2 text-pink-500 flex-col justify-center items-center h-[120px] cursor-pointer rounded-full bg-gradient-to-br from-white to-white shadow shadow-green-500">
                            {/* Optional inner shine */}
                            <div className="text-[22px] text-blue-500">
                                <FaWhatsapp className="text-green-500" />

                            </div>
                            <div className="text-green-500 font-bold text-xl">BulkReply
                            </div>
                            <div className="w-[20px] h-[20px] bg-white/40 rounded-full absolute top-1 left-1 blur-sm" />
                        </motion.div>
                    </div>
                    <div className="w-[300px] h-[300px]   rounded-full bg-white flex justify-center  items-center">
                        <div className="text-lg font-extrabold text-center text-black  ">
                            <div className="space-y-4 flex flex-col ">
                                <div className="text-sm">
                                    Our <span className="text-purple-800">Apps</span> that made for <span className="text-purple-800">US</span>
                                </div>
                                <button className="inline-flex text-sm items-center gap-3 px-6 py-2 bg-purple-600 text-black rounded-full shadow-lg hover:bg-purple-700 transition">
                                    <FaRobot className="text-md" />
                                    View All Apps
                                    <FaArrowRight className="text-md" />
                                </button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div className="max-w-7xl  mx-auto md:mt-10">
                <div className=" md:py-16   ">
                    <div
                        ref={sectionRef}
                        className="md:py-16 px-4 sm:px-6 "
                    >
                        <div className="grid md:grid-cols-3 gap-6 max-w-7xl mx-auto">
                            {stats.map((stat, index) => (
                                <motion.div
                                    key={index}
                                    initial={{ opacity: 0, y: 40 }}
                                    animate={isInView ? { opacity: 1, y: 0 } : {}}
                                    transition={{ delay: index * 0.3, duration: 0.8, ease: "easeOut" }}
                                    className="bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl p-6 sm:p-10 shadow-xl hover:scale-105 transform transition duration-300 ease-in-out"
                                >
                                    <AnimatedCounter
                                        target={stat.value}
                                        currency={stat.currency}
                                        duration={2000}
                                        trigger={isInView}
                                    />
                                    <p className="text-black text-sm text-center mt-4 leading-relaxed">
                                        {stat.label}
                                    </p>
                                </motion.div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
            <div className="max-w-7xl mx-auto mt-10">
                <div className="text-primary-800 text-3xl text-center font-extrabold">Features</div>
                <div className="text-center text-4xl mt-2">Powerfull features to <span className="text-primary-800">Elevates</span> your workflow</div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-10 ">
                    <div className="backdrop-blur-md bg-white/10 border-white/20 shadow-xl rounded-lg p-6 ">
                        <div  ><TbAutomation className="shadow shadow-blue-500 block mx-auto bg-white rounded-full p-1 text-blue-500" size={56} /></div>
                        <div className="text-2xl mt-2 text-center">Automation Workflows</div>
                        <div>Create, manage, and automate repetitive tasks. This includes email marketing, social media scheduling, and more, saving time and ensuring consistency.</div>
                    </div>
                    <div className="backdrop-blur-md bg-white/10 border-white/20 shadow-xl rounded-lg p-6 ">
                        <div  ><LiaToolsSolid className="shadow shadow-red-500 block mx-auto bg-white rounded-full p-1 text-red-500" size={56} /></div>
                        <div className="text-2xl mt-2 text-center">Collaborative Tools
                        </div>
                        <div>Share access to teams and collaborate in real-time on marketing and automation efforts.</div>
                    </div>
                    <div className="backdrop-blur-md bg-white/10 border-white/20 shadow-xl rounded-lg p-6 ">
                        <div  ><SiCustomink className=" shadow shadow-green-500 block mx-auto bg-white rounded-full p-1 text-green-500" size={56} /></div>
                        <div className="text-2xl mt-2 text-center">Custom Workflows</div>
                        <div>Ability to create tailored workflows for different aspects of your business, whether it’s customer support, product launches, or promotions.</div>
                    </div>
                    <div className="backdrop-blur-md bg-white/10 border-white/20 shadow-xl rounded-lg p-6 ">
                        <div  ><TbTargetArrow className=" block shadow shadow-yellow-500 mx-auto bg-white rounded-full p-1 text-yellow-500" size={56} /></div>
                        <div className="text-2xl mt-2 text-center">Multi-Channel Marketing
                        </div>
                        <div>
                            Manage and automate marketing across various channels, including email, social media, and SMS, all from one platform.
                        </div>
                    </div>
                    <div className="backdrop-blur-md bg-white/10 border-white/20 shadow-xl rounded-lg p-6 ">
                        <div  ><FaStore className=" block mx-auto bg-white shadow shadow-cyan-500 rounded-full p-1 text-cyan-500" size={56} /></div>
                        <div className="text-2xl mt-2 text-center">E-commerce Integration</div>
                        <div>Tools for managing sales funnels, automating product promotions, and enhancing customer experience on e-commerce platforms.</div>
                    </div>
                    <div className="backdrop-blur-md bg-white/10 border-white/20 shadow-xl rounded-lg p-6 ">
                        <div  ><TbReportSearch className=" block mx-auto bg-white shadow  shadow-pink-500 rounded-full p-1 text-pink-500" size={56} /></div>
                        <div className="text-2xl mt-2 text-center">Analytics and Reporting
                        </div>
                        <div>Real-time analytics and data-driven insights into campaigns, customer behavior, and platform performance, allowing better decision-making.</div>
                    </div>
                    <div></div>

                </div>
            </div>
            {/* subscription section */}
            <section id="pricing" className="subscriptionSection md:py-10 px-3 transition duration-500  text-black max-w-7xl mx-auto md:mt-10">
                <div className="text-primary-800 text-center text-2xl md:text-4xl font-bold">Pricing</div>
                <div className="text-center text-2xl md:text-4xl font-bold">Choose Your <span className="text-primary-800">Plan</span></div>
                {/* <div className="flex gap-3 justify-center items-center mt-10">
          <span className="text-2xl">Monthly</span>
          <div><ToggleButton subscription={subscription} setsubscription={setsubscription} /></div>

          <span className="text-2xl">Yearly</span>
        </div> */}
                {!subscription &&
                    <div>
                        <div className="grid grid-cols-1  md:grid-cols-2  lg:grid-cols-3 text-black  gap-7 mt-5 md:mt-20">
                            <div
                                ref={divRef}
                                className="shadow-md group cursor-pointer h-[600px] px-10 py-10 bg-white rounded-lg 
       transition-all duration-200 hover:bg-primary-500 hover:text-white"
                            >
                                <h3 className="text-2xl font-extrabold  hover:text-white text-center border-b border-dashed pb-3">
                                    Free
                                </h3>

                                <h4 className="mt-5 text-center text-3xl font-bold">
                                    ₹0.00 INR
                                    <sub className="text-sm text-gray-500 group-hover:text-white">/monthly</sub>
                                </h4>

                                <h4 className="mt-10 text-center text-3xl font-bold">
                                    ₹0.00 INR
                                    <sub className="text-sm text-gray-500 group-hover:text-white">/yearly</sub>
                                </h4>

                                <div className="underline text-black group-hover:text-white mt-6 border-b border-dashed pb-4 text-center cursor-pointer">
                                    + WhatsApp Cloud Messaging Charges
                                </div>

                                <h4 className="text-black group-hover:text-white text-center text-[18px] mt-6">
                                    <span className="font-bold group-hover:text-white">2</span> Contacts
                                </h4>

                                <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                    <span className="font-bold ">5</span> Campaigns Per Month
                                </h4>

                                <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                    <span className="font-bold">0</span> Bot Replies
                                </h4>

                                <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                    <span className="font-bold ">0</span> Bot Flows
                                </h4>

                                <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                    <span className="font-bold">0</span> Contact Custom Fields
                                </h4>

                                <h4 className="text-black  group-hover:text-white text-center text-[18px] mt-1">
                                    <span className="font-bold  hover:text-black">0</span> Team Members/Agents
                                </h4>

                                <h4 className="text-black group-hover:text-white inline-block flex items-center justify-center text-center text-[18px] mt-1">
                                    <span className="font-bold text-red-500">
                                        <RxCross2 />
                                    </span>{" "}
                                    AI Chat Bot
                                </h4>

                                <h4 className="text-black group-hover:text-white inline-block flex items-center justify-center text-center text-[18px] mt-1">
                                    <span className="font-bold text-red-500">
                                        <RxCross2 />
                                    </span>{" "}
                                    API and Webhook Access
                                </h4>
                            </div>
                            <div
                                ref={divRef}
                                className="shadow-md group cursor-pointer h-[600px] px-10 py-10 bg-white rounded-lg 
       transition-all duration-200 hover:bg-primary-500 hover:text-black"
                            >
                                <h3 className="text-2xl font-extrabold  group-hover:text-white text-center border-b border-dashed pb-3">
                                    <div className="flex justify-center items-center gap-2">
                                        <MdRocketLaunch className="text-purple-500" />
                                        <div>Starter Blast</div>
                                    </div>
                                </h3>
                                <div className="text-black group-hover:text-white">
                                    <h4 className="mt-5 text-center text-3xl font-bold">
                                        ₹2,999.00 INR
                                        <sub className="text-sm text-black group-hover:text-white">/monthly</sub>
                                    </h4>

                                    <h4 className="mt-10 text-center text-3xl font-bold">
                                        ₹29.999.00 INR
                                        <sub className="text-sm text-black group-hover:text-white">/yearly</sub>
                                    </h4>

                                    <div className="underline text-black group-hover:text-white mt-6 border-b border-dashed pb-4 text-center cursor-pointer">
                                        + WhatsApp Cloud Messaging Charges
                                    </div>

                                    <h4 className="text-black  group-hover:text-white text-center text-[18px] mt-6">
                                        <span className="font-bold group-hover:text-white">100</span> Contacts
                                    </h4>

                                    <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                        <span className="font-bold ">50</span> Campaigns Per Month
                                    </h4>

                                    <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                        <span className="font-bold  hover:text-black">2</span> Bot Replies
                                    </h4>

                                    <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                        <span className="font-bold  ">1</span> Bot Flows
                                    </h4>

                                    <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                        <span className="font-bold  hover:text-black">5</span> Contact Custom Fields
                                    </h4>

                                    <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                        <span className="font-bold">5</span> Team Members/Agents
                                    </h4>

                                    <h4 className="text-black  group-hover:text-white inline-block flex items-center justify-center text-center text-[18px] mt-1">
                                        <span className="font-bold text-green-500">
                                            <TiTick />
                                        </span>{" "}
                                        AI Chat Bot
                                    </h4>

                                    <h4 className="text-black group-hover:text-white inline-block flex items-center justify-center text-center text-[18px] mt-1">
                                        <span className="font-bold text-green-500">
                                            <TiTick />
                                        </span>{" "}
                                        API and Webhook Access
                                    </h4>
                                </div>
                            </div>
                            <div
                                ref={divRef}
                                className="shadow-md cursor-pointer h-[600px] px-10 py-10 bg-white rounded-lg 
       transition-all duration-200 group hover:bg-primary-500 hover:text-white"
                            >
                                <h3 className="text-2xl font-extrabold  hover:text-black text-center border-b border-dashed pb-3">
                                    <div className="flex justify-center items-center gap-2">
                                        <GiDiamondTrophy className="text-blue-500 text-2xl" />
                                        <div>Enterprise Max</div>
                                    </div>
                                </h3>

                                <h4 className="mt-5 text-center text-3xl font-bold">
                                    ₹5,999.00 INR
                                    <sub className="text-sm text-black group-hover:text-white">/monthly</sub>
                                </h4>

                                <h4 className="mt-10 text-center text-3xl font-bold">
                                    ₹49,999.00 INR
                                    <sub className="text-sm text-black group-hover:text-white">/yearly</sub>
                                </h4>

                                <div className="underline text-black group-hover:text-white mt-6 border-b border-dashed pb-4 text-center cursor-pointer">
                                    + WhatsApp Cloud Messaging Charges
                                </div>

                                <h4 className="text-black group-hover:text-white text-center text-[18px] mt-6">
                                    <span className="font-bold ">Unlimited</span> Contacts
                                </h4>

                                <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                    <span className="font-bold ">Unlimited</span> Campaigns Per Month
                                </h4>

                                <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                    <span className="font-bold ">Unlimited</span> Bot Replies
                                </h4>

                                <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                    <span className="font-bold  hover:text-black">Unlimited</span> Bot Flows
                                </h4>

                                <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                    <span className="font-bold">10</span> Contact Custom Fields
                                </h4>

                                <h4 className="text-black group-hover:text-white text-center text-[18px] mt-1">
                                    <span className="font-bold ">10</span> Team Members/Agents
                                </h4>

                                <h4 className="text-black group-hover:text-white inline-block flex items-center justify-center text-center text-[18px] mt-1">
                                    <span className="font-bold text-green-500">
                                        <TiTick />
                                    </span>{" "}
                                    AI Chat Bot
                                </h4>

                                <h4 className="text-black  group-hover:text-white inline-block flex items-center justify-center text-center text-[18px] mt-1">
                                    <span className="font-bold text-green-500">
                                        <TiTick />
                                    </span>{" "}
                                    API and Webhook Access
                                </h4>
                            </div>
                        </div>
                    </div>}


                <div>





                </div>


                {subscription && <div className="border border-black py-20 mt-10">yearly</div>}
            </section>




            <div>
                <div className="max-w-7xl mx-auto mt-10">
                    <div className="font-bold text-xl text-center text-primary-800">Testimonials</div>
                    <div className="text-center text-3xl">What our <span className="text-primary-800">Users</span> say</div>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-10">
                        {testimonials.map(({ _id, quote, author, designation }) => (
                            <div key={_id} className="shadow-lg shadow-gray-50 p-5">
                                <div className="grid grid-cols-3 gap-3 justify-center items-center">
                                    <div className="w-[88px] h-[88px] rounded-full border overflow-hidden">
                                        <img
                                            className="rounded-full w-full h-full object-cover"
                                            src="https://images.unsplash.com/photo-1613053341085-db794820ce43?w=900&auto=format&fit=crop&q=60"
                                            alt={author}
                                        />
                                    </div>
                                    <div className="col-span-2">
                                        <h3 className="text-lg font-semibold">{author}</h3>
                                        <h4 className="text-sm text-gray-500">{designation}</h4>
                                        <div className="text-yellow-500 flex gap-1 mt-1">
                                            {[...Array(5)].map((_, i) => (
                                                <IoStarOutline key={i} />
                                            ))}
                                        </div>
                                    </div>
                                </div>
                                <div className="mt-4 text-sm text-gray-700 italic">“{quote}”</div>
                            </div>
                        ))}
                    </div>
                    <div>
                        <div className="max-w-7xl">
                            {/* <div className="text-2xl font-bold text-center mt-10">Grow with <span className="text-purple-800 text-3xl  font-bold">SabNode</span></div> */}
                        </div>
                    </div>
                </div>
                <footer className="mt-20 bg-primary-600 text-white rounded-md">
                    <div className="max-w-7xl mx-auto px-6 py-10 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-10">
                        {/* Brand Info */}
                        <div className="md:col-span-2 space-y-4 text-center md:text-left">
                            <h2 className="text-3xl font-bold underline cursor-pointer">Sabnode</h2>
                            <p className="text-sm leading-relaxed text-gray-200">
                                Discover the latest trends in web design that can enhance your online presence. From minimalist
                                aesthetics to interactive elements, find out what’s shaping the future of web design.
                            </p>
                            <div className="flex justify-center md:justify-start gap-4 text-xl text-white">
                                <CiFacebook
                                    onClick={() => handleIconClick(socialMediaLinks.facebook)}
                                    className="hover:text-gray-300 cursor-pointer"
                                />
                                <FaWhatsapp
                                    onClick={() => handleIconClick(socialMediaLinks.twitter)}
                                    className="hover:text-gray-300 cursor-pointer"
                                />
                                <BsInstagram
                                    onClick={() => handleIconClick(socialMediaLinks.instagram)}
                                    className="hover:text-gray-300 cursor-pointer"
                                />
                                <LiaLinkedin
                                    onClick={() => handleIconClick(socialMediaLinks.linkedin)}
                                    className="hover:text-gray-300 cursor-pointer"
                                />
                            </div>
                        </div>

                        {/* Products */}
                        <div>
                            <h2 className="text-xl font-semibold underline text-center mb-4">Products</h2>
                            <ul className=" text-sm flex gap-3 md:block md:space-y-2 items-center justify-center gap-2 text-center">
                                <li className="hover:underline cursor-pointer">Wachat</li>
                                <li className="hover:underline cursor-pointer md:block  gap-1 flex items-center">
                                    <span className="md:hidden block">|</span> Botpion</li>
                                <li className="hover:underline cursor-pointer md:block gap-1 flex items-center">
                                    <span className="md:hidden block">|</span> Rm</li>
                                <li className="hover:underline cursor-pointer gap-1 md:block flex items-center">
                                    <span className="md:hidden block">|</span> Bio Link</li>
                                <li className="hover:underline cursor-pointer gap-1 md:block flex items-center">
                                    <span className="md:hidden block">|</span> Solvdesk</li>
                            </ul>
                        </div>

                        {/* Resources */}
                        <div>
                            <h2 className="text-xl font-semibold underline  text-center mb-4">Resources</h2>
                            <ul className="   text-sm text-center">
                                <div className="flex items-center md:space-y-2 justify-center gap-2 md:block">
                                    <li className="hover:underline cursor-pointer">Blogs</li>
                                    <li className="hover:underline cursor-pointer md:block gap-1 flex items-center">
                                        <span className="md:hidden block">|</span> About Us</li>
                                </div>
                            </ul>
                        </div>

                        {/* Get In Touch */}
                        <div>
                            <h2 className="text-xl font-semibold underline text-center mb-4">Get In Touch</h2>
                            <ul className=" text-sm text-center">
                                <div className="flex justify-center items-center md:block md:space-y-2 gap-2">
                                    <li className="hover:underline cursor-pointer">  FAQs</li>
                                    <li className="hover:underline cursor-pointer md:block gap-1 flex items-center">
                                        <span className="md:hidden block">|</span> Contact Us</li>
                                    <li className="hover:underline cursor-pointer md:block  gap-1 flex items-center">
                                        <span className="md:hidden block">|</span> Sign In</li>
                                    <li className="hover:underline cursor-pointer md:block gap-1 flex items-center">
                                        <span className="md:hidden block">|</span> Sign up</li>
                                </div>
                            </ul>
                        </div>

                        {/* Legal */}
                        <div>
                            <h2 className="text-xl font-semibold underline text-center mb-4">Legal</h2>
                            <ul className=" text-sm  text-center">
                                <div className="flex justify-center items-center  md:block md:space-y-2 gap-1">
                                    <li className="hover:underline cursor-pointer">
                                        Terms and Conditions</li>

                                    <li onClick={() => openInNewTab(privacyPolicyUrl)} className="hover:underline flex md:block gap-1 items-center cursor-pointer">
                                        <span className="md:hidden block">|</span >  Privacy Policy</li>
                                    <li onClick={() => openInNewTab(termsOfServiceUrl)} className="hover:underline cursor-pointer gap-1 md:block flex items-center">
                                        <span className="md:hidden block">|</span> Refund Policy</li>
                                </div>
                            </ul>
                        </div>
                    </div>

                    <div className="text-center py-4 text-sm bg-primary-700 text-gray-200 rounded-b-md">
                        © 2025 All Rights Reserved by {domain}
                    </div>
                </footer>

            </div>
        </div>


    );
}


//biolink:24 138,botpion:546,369;crm:24,138;uptime:-587,282;solvdesk:-357,364;wachat:546,